# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox      # janela de diálogo

import mariadb
conexao = mariadb.connect(host="localhost", user="root",
                          password="", database = "escola")
cursor = conexao.cursor()
print("Conectado ao banco de dados.")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 232)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_nome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_nome.setObjectName("label_nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_nome)
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_nome)
        self.label_curso = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_curso.setObjectName("label_curso")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_curso)
        self.comboBox_curso = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_curso.setObjectName("comboBox_curso")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_curso)
        self.label_turno = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_turno.setObjectName("label_turno")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_turno)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_manha = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_manha.setObjectName("radioButton_manha")
        self.horizontalLayout.addWidget(self.radioButton_manha)
        self.radioButton_tarde = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_tarde.setObjectName("radioButton_tarde")
        self.horizontalLayout.addWidget(self.radioButton_tarde)
        self.radioButton_noite = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_noite.setObjectName("radioButton_noite")
        self.horizontalLayout.addWidget(self.radioButton_noite)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.label_extra = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_extra.setObjectName("label_extra")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_extra)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_atleta = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_atleta.setObjectName("checkBox_atleta")
        self.horizontalLayout_2.addWidget(self.checkBox_atleta)
        self.checkBox_bolsista = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_bolsista.setObjectName("checkBox_bolsista")
        self.horizontalLayout_2.addWidget(self.checkBox_bolsista)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_2)
        self.label_obs = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_obs.setObjectName("label_obs")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_obs)
        self.plainTextEdit_obs = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_obs.setObjectName("plainTextEdit_obs")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextEdit_obs)
        self.pushButton_salvar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.pushButton_salvar.clicked.connect(self.salvar)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton_salvar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro de Aluno"))
        self.label_nome.setText(_translate("MainWindow", "Nome:"))
        self.label_curso.setText(_translate("MainWindow", "Curso:"))
        self.comboBox_curso.setItemText(0, _translate("MainWindow", "Edificações"))
        self.comboBox_curso.setItemText(1, _translate("MainWindow", "Eletrotécnica"))
        self.comboBox_curso.setItemText(2, _translate("MainWindow", "Informática"))
        self.comboBox_curso.setItemText(3, _translate("MainWindow", "Mecânica"))
        self.label_turno.setText(_translate("MainWindow", "Turno:"))
        self.radioButton_manha.setText(_translate("MainWindow", "Manhã"))
        self.radioButton_tarde.setText(_translate("MainWindow", "Tarde"))
        self.radioButton_noite.setText(_translate("MainWindow", "Noite"))
        self.label_extra.setText(_translate("MainWindow", "Extra:"))
        self.checkBox_atleta.setText(_translate("MainWindow", "Atleta"))
        self.checkBox_bolsista.setText(_translate("MainWindow", "Bolsista"))
        self.label_obs.setText(_translate("MainWindow", "Obs.:"))
        self.pushButton_salvar.setText(_translate("MainWindow", "SALVAR"))

    
    def salvar(self):
        #criar variáveis e capturar os dados
        nome = self.lineEdit_nome.text()
        
        curso = self.comboBox_curso.currentText()
        
        turno = ""
        if self.radioButton_manha.isChecked():
            turno = "Manhã"
        elif self.radioButton_tarde.isChecked():
            turno = "Tarde"
        elif self.radioButton_noite.isChecked():
            turno = "Noite"
        
        atleta = "não"
        if self.checkBox_atleta.isChecked():
            atleta = "sim"
        
        bolsista = "não"
        if self.checkBox_bolsista.isChecked():
            bolsista = "sim"
            
        obs = self.plainTextEdit_obs.toPlainText()
        
        comando = "INSERT INTO aluno VALUES(null,%s,%s,%s,%s,%s,%s)"
        cursor.execute(comando, (nome,curso,turno,atleta,bolsista,obs) )
        conexao.commit()
        #print("Gravado com sucesso.")
        
        msg = QMessageBox()
        msg.setWindowTitle("Aviso")
        msg.setText("Gravado com sucesso.")
        msg.exec()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
