# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(253, 150)
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_acesso = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_acesso.setObjectName("label_acesso")
        self.verticalLayout.addWidget(self.label_acesso)
        self.label_usuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_usuario.setObjectName("label_usuario")
        self.verticalLayout.addWidget(self.label_usuario)
        self.lineEdit_usuario = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_usuario.setObjectName("lineEdit_usuario")
        self.verticalLayout.addWidget(self.lineEdit_usuario)
        self.label_senha = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_senha.setObjectName("label_senha")
        self.verticalLayout.addWidget(self.label_senha)
        self.lineEdit_senha = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.verticalLayout.addWidget(self.lineEdit_senha)
        self.pushButton_entrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_entrar.setObjectName("pushButton_entrar")
        
        self.pushButton_entrar.clicked.connect(self.entrar)
        
        self.verticalLayout.addWidget(self.pushButton_entrar)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login do Sistema"))
        self.label_acesso.setText(_translate("Login", "ACESSO AO SISTEMA"))
        self.label_usuario.setText(_translate("Login", "Usuário:"))
        self.label_senha.setText(_translate("Login", "Senha:"))
        self.pushButton_entrar.setText(_translate("Login", "ENTRAR"))


    def entrar(self):
        #capturar o ususuário e senha digitados
        usuario = self.lineEdit_usuario.text()
        senha   = self.lineEdit_senha.text()
        # comparar a digitação com os dados aceitos
        if usuario == "admin" and senha == "legal":
            from menu import Ui_Menu
            self.janela = QtWidgets.QMainWindow()
            self.menu = Ui_Menu()
            self.menu.setupUi(self.janela)
            self.janela.show() # mostra a tela com o menu
            Login.close()     # fecha a tela de login
        else:
            msg = QMessageBox()
            msg.setText("Acesso negado.")
            msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
    
    
    
    
    
    