# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(273, 168)
        self.centralwidget = QtWidgets.QWidget(parent=Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_cadastro = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cadastro.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cadastro.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_cadastro.setIcon(icon)
        self.pushButton_cadastro.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_cadastro.setObjectName("pushButton_cadastro")
        
        self.pushButton_cadastro.clicked.connect(self.abrir_cadastro)
        
        self.gridLayout.addWidget(self.pushButton_cadastro, 0, 0, 1, 1)
        self.pushButton_pesquisa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_pesquisa.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("procurar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_pesquisa.setIcon(icon1)
        self.pushButton_pesquisa.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_pesquisa.setObjectName("pushButton_pesquisa")
        self.gridLayout.addWidget(self.pushButton_pesquisa, 0, 1, 1, 1)
        self.pushButton_ajuda = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_ajuda.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ajuda.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_ajuda.setIcon(icon2)
        self.pushButton_ajuda.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_ajuda.setObjectName("pushButton_ajuda")
        self.gridLayout.addWidget(self.pushButton_ajuda, 1, 0, 1, 1)
        self.pushButton_sair = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_sair.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("sair.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_sair.setIcon(icon3)
        self.pushButton_sair.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_sair.setObjectName("pushButton_sair")
        
        self.pushButton_sair.clicked.connect(self.sair)
        
        self.gridLayout.addWidget(self.pushButton_sair, 1, 1, 1, 1)
        Menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu do Sistema"))

    def abrir_cadastro(self):
        from cadastro import Ui_MainWindow
        self.janela = QtWidgets.QMainWindow()
        self.menu = Ui_MainWindow()
        self.menu.setupUi(self.janela)
        self.janela.show()
    
    def sair(self):
        Menu.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QMainWindow()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec())
